// <auto-generated />
using System;
using HA.TFG.AppFinanzas.BackEnd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HA.TFG.AppFinanzas.BackEnd.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Categoria", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            IdCategoria = new Guid("87a094ed-c89e-8cb7-a230-24e661e6b81e"),
                            Descripcion = "Cualquier tipo de ingreso",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ingresos",
                            TipoMovimiento = "Ingreso"
                        },
                        new
                        {
                            IdCategoria = new Guid("5c1b4a03-8a80-94ec-e3fa-ed108fba5af1"),
                            Descripcion = "Alquiler, hipoteca y gastos del hogar",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vivienda",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("3ca32666-7234-8ffa-1743-87fe755d1b21"),
                            Descripcion = "Compras en supermercado y alimentación en casa",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Supermercado",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("05d99d95-5bd2-d9b4-9bc5-282be6c98ce5"),
                            Descripcion = "Restaurantes, bares y comida para llevar",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Restaurantes",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("e6a6ad16-fd61-835b-3c45-ac310298f556"),
                            Descripcion = "Combustible, transporte público y vehículo",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Transporte",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("0ecb90bb-f405-92d9-9c49-08adb9e43ac3"),
                            Descripcion = "Médico, farmacia y seguros de salud",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Salud",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("104a0f1c-93f3-9160-0052-51d32f85ee7b"),
                            Descripcion = "Cursos, libros y formación",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Educación",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("9a6cf402-04f6-49d4-7cd0-bd0f540040c3"),
                            Descripcion = "Cine, viajes, hobbies y deportes",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ocio y entretenimiento",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("b40532f5-ec9b-8d31-2180-ccb81fe954cf"),
                            Descripcion = "Prendas de vestir y complementos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ropa y calzado",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("ef82c217-d3f9-18c4-a956-b0a414ece3b2"),
                            Descripcion = "Dispositivos, software y suscripciones digitales",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tecnología",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("a44f7452-de22-2136-9cda-9d446f5f86eb"),
                            Descripcion = "Electricidad, agua, gas e internet",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Servicios",
                            TipoMovimiento = "Gasto"
                        },
                        new
                        {
                            IdCategoria = new Guid("c73ebca7-2bf5-fd6e-e041-642b86a9aa02"),
                            Descripcion = "Gastos no clasificados",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Otros gastos",
                            TipoMovimiento = "Gasto"
                        });
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Cuenta", b =>
                {
                    b.Property<Guid>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCuenta");

                    b.ToTable("cuentas", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.CuentaCategoria", b =>
                {
                    b.Property<Guid>("IdCuentaCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCuenta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdCuentaCategoria");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdCuenta", "Nombre")
                        .IsUnique();

                    b.ToTable("cuenta_categorias", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Identidad", b =>
                {
                    b.Property<Guid>("IdIdentidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdAuth0")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIdentidad");

                    b.HasIndex("IdAuth0")
                        .IsUnique();

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_identidades", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Movimiento", b =>
                {
                    b.Property<Guid>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdComprobante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdCuenta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("TipoCambio")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdCuenta");

                    b.ToTable("movimientos", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRol");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.UsuarioCuenta", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCuenta")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario", "IdCuenta");

                    b.HasIndex("IdCuenta");

                    b.ToTable("usuario_cuentas", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.CuentaCategoria", b =>
                {
                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Categoria", "Origen")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Cuenta", "Cuenta")
                        .WithMany("Categorias")
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Identidad", b =>
                {
                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Usuario", null)
                        .WithMany("Identidades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Movimiento", b =>
                {
                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.CuentaCategoria", "Categoria")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.UsuarioCuenta", b =>
                {
                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.UsuarioRol", b =>
                {
                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Cuenta", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.CuentaCategoria", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("HA.TFG.AppFinanzas.BackEnd.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Identidades");
                });
#pragma warning restore 612, 618
        }
    }
}
